package net.sidetopia.cosmetics.jeweling;

public enum JewelingStatus {
    EMPTY,
    FEATURE_DISABLED,
    INVALID_JEWEL,
    NO_RECIPE,
    INVALID_EQUIPMENT,
    AMBIGUOUS_RECIPE,
    MISSING_ENCHANTMENT,
    INVALID_LEVEL,
    KNOWLEDGEBOUND_REQUIRED,
    SYSTEM_DISABLED,
    TIER_TOO_LOW,
    SOCKET_LIMIT_REACHED,
    DUPLICATE_ENCHANTMENT,
    INCOMPATIBLE_ENCHANTMENT,
    READY
}
